[package]
name = "datacert_certificates"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.56.2" }

[addresses]
datacert_certificates = "0x0"
